services:
  nginx:
    container_name : nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
      - ./custom:/data/nginx/custom

volumes:
  data:
  letsencrypt:

networks:
  default:
    external: true
    name: base
